package com.xyzlast.bookstore;

import java.sql.SQLException;
import java.util.Date;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws ClassNotFoundException, SQLException, InstantiationException, IllegalAccessException {
//        BookService bookService = new BookService();
//        System.out.println(bookService.countAll());
//        Book book = new Book();
//        book.setId(1);
//        book.setName("ChangedBookName");
//        book.setAuthor("나야나");
//        book.setComment("이건 뭘까요.");
//        book.setPublishDate(new Date());
//
//        bookService.update(book);
    }
}
